### PR TITLE
Switch to Qute and Web Bundler

### PR DESCRIPTION
**Pull request by ia3andy**

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Cool. Hava a look at the conflicts and lets get this in

**Review by phillip-kruger — APPROVED** [review]

**Comment by ia3andy** [comment]
@phillip-kruger was it working? I was fixing a bug on the esbuild-java :)

**Comment by phillip-kruger** [comment]
Yeah not working. That is ok, we can just do more PR s

**Comment by ia3andy** [comment]
Ok I am working on the fix

**Pull request merged**
